---
params:
  Prolific participant ID: NA
  Pavlovia session ID: NA 
  device type: NA 
  cores: NA
  tardyMs: NA
  excessMs: NA
  date: NA
  kB: NA
  rows: NA
  cols: NA
  system: NA
  browser: NA
  resolution: NA
  computer51Deg: NA
  ok: NA
  unmetNeeds: NA
  error: NA
  warning: NA 
  block condition: NA
  trial: NA
  condition name: NA
  target task: NA
  target kind: NA
  Loudspeaker: NA
  Microphone: NA
  threshold parameter: NA
  order: NA
  experiment: ""
title: "`r paste(unique(params$experiment), collapse = '-')`"
output: html_document
---
```{r, echo = F, inlcude = FALSE, message=FALSE}
library(ggplot2)
source("./constant.R")
```

### `r format(Sys.time(), '%B %d, %Y')`

```{=html}
<style>
.main-container {
    margin-left: 0;
    margin-right: 0;
}
</style>
```

`r instruction`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, inlcude = FALSE, warning=FALSE)
```


```{r, echo = F, inlcude = FALSE, message=FALSE}
library(DT)
library(dplyr)
source("./error report/random_rgb.R")
```

```{css, include = TRUE}
.dataTables_filter {
position:relative; 
float: left !important; 
top:0px;
}
```

```{r, echo = F, include = FALSE}
dt <- tibble(
  `Prolific participant ID` = params$`Prolific participant ID`,
  `Pavlovia session ID` = params$`Pavlovia session ID`,
  `device type` = params$`device type`,
  system = params$system,
  browser = params$browser,
  resolution = params$resolution,
  computer51Deg = params$computer51Deg,
  cores = params$cores,
  tardyMs = params$tardyMs,
  excessMs = params$excessMs,
  date = params$date,
  KB = params$KB,
  rows = params$rows,
  cols= params$cols,
  ok = params$ok,
  unmetNeeds = params$unmetNeeds,
  error = params$error,
  warning = params$warning,
  `block condition` = params$`block condition`,
  trial = params$trial,
  `condition name` = params$`condition name`,
  `target task` = params$`target task`,
  `target kind` = params$`target kind`,
  `threshold parameter` = params$`threshold parameter`,
   Loudspeaker = params$`Loudspeaker`, 
   Microphone =  params$Microphone,
  `order` = params$`order`)
participants <- unique(dt$`Pavlovia session ID`)
prolific_id <- unique(dt$`Prolific participant ID`)
```


```{r, include = TRUE}
set.seed(2023)
datatable(dt,
          class = list(stripe = FALSE),
          selection = 'none',
          filter = "top",
          escape = FALSE,
          width = "200%",
          options = list(
            autoWidth = FALSE,
            paging = FALSE,
            scrollX=TRUE,
            dom = 't',
            language = list(
              info = 'Showing _TOTAL_ entries',
              infoFiltered =  "(filtered from _MAX_ entries)"
            ),
            columnDefs = list(
                         list(visible = FALSE, targets = c(0, 27)),
                         list(orderData = 27, targets = 20),
                         list(
                           targets = c(17),
                           width = '500px',
                           className = 'details-control1',
                           render = JS(
                             "function(data, type, row, meta) {",
                             "return type === 'display' && data.length > 20 ?",
                             "data.substr(0, 20) + '...' : data;",
                             "}"
                           )
                         ),
                         list(
                           targets = c(18),
                           width = '250px',
                           className = 'details-control2',
                           render = JS(
                             "function(data, type, row, meta) {",
                             "return type === 'display' && data.length > 20 ?",
                             "data.substr(0, 20) + '...' : data;",
                             "}"
                           )
                         ),
                         list(
                           targets = c(25),
                           width = '250px',
                           className = 'details-control3',
                           render = JS(
                             "function(data, type, row, meta) {",
                             "return type === 'display' && data.length > 20 ?",
                             "data.substr(0, 20) + '...' : data;",
                             "}"
                           )
                         ),
                         list(
                           targets = c(26),
                           width = '250px',
                           className = 'details-control4',
                           render = JS(
                             "function(data, type, row, meta) {",
                             "return type === 'display' && data.length > 20 ?",
                             "data.substr(0, 20) + '...' : data;",
                             "}"
                           )
                         ),
                         list(
                           targets = c(1),
                           render = JS(
                             "function(data, type, row, meta) {",
                             "return type === 'display' && data.length > 6 ?",
                             "'<span title=\"' + data + '\">' + data.substr(0, 6) + '...</span>' : data;",
                             "}"
                           ),
                           className = 'information-control1'
                         ),
                         list(
                           targets = c(2),
                           render = JS(
                             "function(data, type, row, meta) {",
                             "return type === 'display' && data.length > 6 ?",
                             "'<span title=\"' + data + '\">' + data.substr(0, 6) + '...</span>' : data;",
                             "}"
                           ),
                           className = 'information-control2'
                         ),
                         list(
                           width = '250px',
                           targets = c(5, 6),
                           className = 'dt-center'
                         ),
                         list(
                           width = '50px',
                           targets = c(3, 4, 8, 15, 20),
                           className = 'dt-center'
                         ),
                         list(width = '200px', targets = c(21))
                       )
                     ),
                     callback = JS(data_table_call_back)) %>% 
  formatStyle(names(dt),color = 'black', lineHeight="10px") %>% 
  formatStyle(names(dt)[-1],
              'Pavlovia session ID', 
              backgroundColor = styleEqual(participants, random_rgb(length(participants)))) %>% 
  formatStyle(names(dt)[1],
              'Prolific participant ID', 
              backgroundColor = styleEqual(prolific_id, random_rgb(length(prolific_id))))
```



