# Load all server-side R modules in dependency order.
source("R/utils/logger.R")
source("R/constant.R")
source("R/preprocess.R")
source("R/threshold_and_warning.R")

source("R/report/random_rgb.R")
source("R/report/summary_table.R")
source("R/report/prolific.R")

source("R/plot/mean_median_plot.R")
source("R/plot/regression_plot.R")
source("R/plot/histogram.R")
source("R/plot/diagram.R")
source("R/plot/crowding_plot.R")
source("R/plot/test_retest.R")
source("R/plot/scatter_plots.R")
source("R/plot/readingPlots.R")
source("R/plot/customized_inplot_table.R")
source("R/plot/profile_plot.R")
source("R/plot/simulatedRSVP.R")
source("R/plot/font_aggregated_plots.R")
source("R/plot/acuityPlot.R")
source("R/plot/crowdingrsvp.R")
source("R/plot/repeated-letter-crowding.R")
source("R/plot/durationSecPlot.R")
source("R/plot/participant_styles.R")
source("R/plot/distancePlot.R")
source("R/plot/minDegPlot.R")
source("R/plot/violin_plot.R")
source("R/plot/font_comparision_plots.R")
source("R/plot/auditory_crowding.R")

source("R/utils/sound_plots.R")
source("R/utils/read_json.R")
source("R/utils/formSpree.R")
source("R/utils/utility.R")
source("R/utils/anova_by_font.R")

source("R/server/sound_server.R")
source("R/server/profile_server.R")
source("R/server/staircases_server.R")
source("R/server/timing_server.R")
source("R/server/quality_server.R")
source("R/server/distance_server.R")
source("R/server/form_spree_dash_server.R")
source("R/server/anova_server.R")
source("R/server/stat_server.R")
source("R/server/plots_reading_rsvp_outputs.R")
source("R/server/plots_tab_server.R")
