name: Deploy to shinyapps.io
on:

  # run on any push 
  push:
    branches:
      - main

  # run on request (via button in actions menu)
  workflow_dispatch:
      
jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Install rsconnect
        run: install.packages("rsconnect")
        shell: Rscript {0}
          
      # Step 2: Install R packages
      - name: install everything and deploy
        env:
          RS_TOKEN: ${{ secrets.TOKEN }}
          RS_SECRET: ${{ secrets.SECRET }}
        run: |
          rsconnect::setAccountInfo(name='easyeyes', token=Sys.getenv('RS_TOKEN'), secret=Sys.getenv('RS_SECRET'))
          rsconnect::deployApp(appName = 'easyeyes_app', forceUpdate = TRUE)
        shell: Rscript {0}
          
    
